name: sound_recorder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-348.0.dev <4.0.0'

dependencies:
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_sound_lite: ^8.5.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
